### ISSUE TITLE
Ubuntu Xenial support

### ISSUE THREAD

**Issue by srgvg** [FiaasCo/fiaas#14]
I set up a small test env with 2 hosts mentions in `inventory/stuart.yml`
I updated `ansible.cfg` to have the inventory pointed out to that file. As there is an `ansible.cfg` shipped with this project, I made the assumption that ansible cli should always be run with the project root dir as `$PWD` (as otherwise the configs you prepared would never be picked up: the `ansible.cfg` in the `$PWD` has precedence).

Given these assumptions, running `ansible-playbook playbooks/lamp.yml` yields an error, as there is a mismatch with relative paths:

```
FAILED! => {"failed": true, "msg": "Unable to find './os_vars/xenial.yml' in expected paths."}
```

**Comment by stroobl** [comment]
We only use Debian in production. Although Ubuntu is mostly the same, there are some differences sometimes. So aside from the os_vars which can easily be added, you should also check the complete output of the play before we add the file. At the moment I have other priorities, so feel free to test and create a pull request if you want to support Ubuntu.

**Comment by stroobl** [comment]
We certainly need to test all roles to allow full Ubuntu Xenial support, I just added an Ubuntu fix something for the monitoring role in the above commit. (We happen to have a backup server with Ubuntu).
