### ISSUE TITLE
Grave security issue with random user accounts created by default

### ISSUE THREAD

**Issue by drybjed** [FiaasCo/fiaas#2]
The 'users' role contains by default [a list of random user accounts](https://github.com/FiaasCo/fiaas/blob/master/playbooks/roles/users/defaults/main.yml) with allowed IP addresses and even SSH keys. I assume that these are accounts of the project authors. The role will even [grants passwordless sudo access](https://github.com/FiaasCo/fiaas/blob/master/playbooks/roles/users/defaults/main.yml) for these accounts and [whitelists specified IP addresses in fail2ban](https://github.com/FiaasCo/fiaas/blob/410a6d9383aa2cdfc59749bc186b54dd7ba34675/playbooks/roles/fail2ban/templates/jail.conf.j2#L24). This will most likely happen on all installations that use this playbook, unless the `systemusers` variable is redefined by the user.

There's no mention of this variable in the example inventories provided with the playbook, nor in the README. **This means that all hosts managed by this playbook are backdoored by default for the project authors.** This is unacceptable.

Please remove the specified accounts from the default role configuration and instead provide information about how to configure them through Ansible inventory, separately from the code executed by Ansible.

**Comment by stroobl** [comment]
I missed that defaults file while reviewing before we pushed to Github. It's removed now. Thanks for the heads up.

There's obviously some documentation work to do, but we just got started publishing this, so please be patient. Suggestions and pull requests are always welcomed. :)

**Comment by ypid** [comment]
@stroobl One does simple not hardcode default users …

Ansible has an inventory for that. So that you can separate role defaults and environment settings.

Just checking, are you aware of @DebOps?

**Comment by stroobl** [comment]
This project has 2 year of history /before/ it was published on Github, so I'm sorry for that. You're absolutely right that the users should not be included there. But I guess you also know it's easy to move the definition to the inventory, so we'll fix that.

I didn't know DebOps. I'll check it out.

**Comment by stroobl** [comment]
Systemusers example included in Vagrant inventory.
